"""Remove ConnectorConfiguration table and update McpServer with configuration fields

Revision ID: 1a19129680dc
Revises: f1fb9ea4a9e2
Create Date: 2025-10-01 22:37:00.938119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a19129680dc'
down_revision: Union[str, Sequence[str], None] = 'f1fb9ea4a9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_configurations_connector_id'), table_name='connector_configurations')
    op.drop_table('connector_configurations')
    op.add_column('mcp_servers', sa.Column('server_id', sa.String(), nullable=False))
    op.add_column('mcp_servers', sa.Column('server_name', sa.String(), nullable=False))
    op.add_column('mcp_servers', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.create_index(op.f('ix_mcp_servers_server_id'), 'mcp_servers', ['server_id'], unique=False)
    op.drop_column('mcp_servers', 'description')
    op.drop_column('mcp_servers', 'url')
    op.drop_column('mcp_servers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mcp_servers', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mcp_servers_server_id'), table_name='mcp_servers')
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=False)
    op.drop_column('mcp_servers', 'configuration')
    op.drop_column('mcp_servers', 'server_name')
    op.drop_column('mcp_servers', 'server_id')
    op.create_table('connector_configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connector_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('connector_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('connector_configurations_pkey'))
    )
    op.create_index(op.f('ix_connector_configurations_connector_id'), 'connector_configurations', ['connector_id'], unique=False)
    # ### end Alembic commands ###
