"""add_mcp_server_tools_table

Revision ID: 472e4f9de459
Revises: 4ee661f6d6bc
Create Date: 2025-10-02 21:40:38.775164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '472e4f9de459'
down_revision: Union[str, Sequence[str], None] = '4ee661f6d6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcp_server_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_server_tools')
    # ### end Alembic commands ###
