"""Add user relationships to all models

Revision ID: 5ddae4192e08
Revises: afcc8ff55755
Create Date: 2025-10-09 11:45:51.801092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddae4192e08'
down_revision: Union[str, Sequence[str], None] = 'afcc8ff55755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connectors', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'mcp_connectors', 'user', ['user_id'], ['id'])
    op.add_column('mcp_server_tokens', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'mcp_server_tokens', 'user', ['user_id'], ['id'])
    op.add_column('mcp_server_tools', sa.Column('user_id', sa.Uuid(), nullable=True))
    
    # Update existing NULL template_name values to a default value before making it NOT NULL
    op.execute("UPDATE mcp_server_tools SET template_name = 'default_template' WHERE template_name IS NULL")
    
    op.alter_column('mcp_server_tools', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'mcp_server_tools', 'user', ['user_id'], ['id'])
    op.add_column('mcp_servers', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'mcp_servers', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcp_servers', type_='foreignkey')
    op.drop_column('mcp_servers', 'user_id')
    op.drop_constraint(None, 'mcp_server_tools', type_='foreignkey')
    op.alter_column('mcp_server_tools', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mcp_server_tools', 'user_id')
    op.drop_constraint(None, 'mcp_server_tokens', type_='foreignkey')
    op.drop_column('mcp_server_tokens', 'user_id')
    op.drop_constraint(None, 'mcp_connectors', type_='foreignkey')
    op.drop_column('mcp_connectors', 'user_id')
    # ### end Alembic commands ###
