"""Add created_at and updated_at to McpServerTool

Revision ID: 902b28846d94
Revises: 925f850e78fc
Create Date: 2025-10-06 18:08:33.867820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902b28846d94'
down_revision: Union[str, Sequence[str], None] = '925f850e78fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('mcp_server_tools', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('mcp_server_tools', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing records with current timestamp
    op.execute("UPDATE mcp_server_tools SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL OR updated_at IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('mcp_server_tools', 'created_at', nullable=False)
    op.alter_column('mcp_server_tools', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server_tools', 'updated_at')
    op.drop_column('mcp_server_tools', 'created_at')
    # ### end Alembic commands ###
