"""update_mcp_server_tools_make_template_fields_nullable

Revision ID: d62570fd4964
Revises: 124b34561ecc
Create Date: 2025-10-09 22:18:23.908653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62570fd4964'
down_revision: Union[str, Sequence[str], None] = '124b34561ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_server_tools', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_server_tools', 'template_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
