"""add_mode_and_secret_to_connectors

Revision ID: e79dee610a78
Revises: f8afdb2a25f6
Create Date: 2025-10-13 15:46:53.724716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79dee610a78'
down_revision: Union[str, Sequence[str], None] = 'f8afdb2a25f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add mode column with default value for existing rows
    op.add_column('mcp_connectors', sa.Column('mode', sa.String(length=20), nullable=False, server_default='sync'))
    op.add_column('mcp_connectors', sa.Column('secret', sa.LargeBinary(), nullable=True))
    op.alter_column('mcp_server_tokens', 'mcp_server_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mcp_server_tools', 'mcp_server_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mcp_servers', 'connector_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'connector_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mcp_server_tools', 'mcp_server_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mcp_server_tokens', 'mcp_server_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('mcp_connectors', 'secret')
    op.drop_column('mcp_connectors', 'mode')
    # ### end Alembic commands ###
