"""add_template_name_and_template_args_to_mcp_server_tools

Revision ID: 0c86ec73bbae
Revises: 4b1755316ae8
Create Date: 2025-10-08 09:04:47.515139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c86ec73bbae"
down_revision: Union[str, Sequence[str], None] = "4b1755316ae8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_server_tools",
        sa.Column("template_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "template_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_server_tools", "template_args")
    op.drop_column("mcp_server_tools", "template_name")
    # ### end Alembic commands ###
