"""fix_foreign_key_constraints_remove_quotes

Revision ID: 124b34561ecc
Revises: 5ddae4192e08
Create Date: 2025-10-09 22:05:13.855087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "124b34561ecc"
down_revision: Union[str, Sequence[str], None] = "5ddae4192e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
