"""update mcp_server_tools model

Revision ID: 2ef36bf0c572
Revises: 472e4f9de459
Create Date: 2025-10-04 22:56:36.807861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ef36bf0c572"
down_revision: Union[str, Sequence[str], None] = "472e4f9de459"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "tool_collection", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("mcp_server_tools", "tool_name")
    op.drop_column("mcp_server_tools", "created_at")
    op.drop_column("mcp_server_tools", "updated_at")
    op.drop_column("mcp_server_tools", "tool_output_schema")
    op.drop_column("mcp_server_tools", "tool_title")
    op.drop_column("mcp_server_tools", "is_active")
    op.drop_column("mcp_server_tools", "tool_input_schema")
    op.drop_column("mcp_server_tools", "tool_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "tool_description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "tool_input_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column("tool_title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "tool_output_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column("tool_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mcp_server_tools", "tool_collection")
    # ### end Alembic commands ###
