"""add_server_url_to_mcp_servers

Revision ID: 4b1755316ae8
Revises: 902b28846d94
Create Date: 2025-10-07 18:18:09.955385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4b1755316ae8"
down_revision: Union[str, Sequence[str], None] = "902b28846d94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column("server_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_servers", "server_url")
    # ### end Alembic commands ###
