"""remove_server_id_add_connector_name_and_server_name

Revision ID: 4ee661f6d6bc
Revises: 910ded28396f
Create Date: 2025-10-02 10:56:36.551883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ee661f6d6bc"
down_revision: Union[str, Sequence[str], None] = "910ded28396f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add connector_name as nullable first
    op.add_column(
        "mcp_servers", sa.Column("connector_name", sa.String(), nullable=True)
    )

    # Populate connector_name from server_id for existing rows
    # Assuming server_id format was something like "sql_db" or similar
    op.execute(
        "UPDATE mcp_servers SET connector_name = server_id WHERE connector_name IS NULL"
    )

    # Now make it NOT NULL
    op.alter_column("mcp_servers", "connector_name", nullable=False)

    op.drop_index(op.f("ix_mcp_servers_server_id"), table_name="mcp_servers")
    op.drop_column("mcp_servers", "server_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column("server_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_mcp_servers_server_id"), "mcp_servers", ["server_id"], unique=False
    )
    op.drop_column("mcp_servers", "connector_name")
    # ### end Alembic commands ###
