"""Update McpConnector model with new fields

Revision ID: 756941f2c55a
Revises: c2608651c99d
Create Date: 2025-10-05 14:51:39.619285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "756941f2c55a"
down_revision: Union[str, Sequence[str], None] = "c2608651c99d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_connectors",
        sa.Column(
            "tools_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "mcp_connectors",
        sa.Column(
            "templates_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "mcp_connectors",
        sa.Column(
            "server_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "mcp_connectors",
        "logo_url",
        existing_type=postgresql.BYTEA(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_column("mcp_connectors", "configuration")

    # Update existing records to populate connector_id from connector_name
    op.execute(
        "UPDATE mcp_servers SET connector_id = connector_name WHERE connector_id IS NULL"
    )

    op.alter_column(
        "mcp_servers", "connector_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("mcp_servers", "connector_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column("connector_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "mcp_servers", "connector_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.add_column(
        "mcp_connectors",
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "mcp_connectors",
        "logo_url",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    op.drop_column("mcp_connectors", "server_config")
    op.drop_column("mcp_connectors", "templates_config")
    op.drop_column("mcp_connectors", "tools_config")
    # ### end Alembic commands ###
