"""Remove custom role field, use fastapi-users is_superuser

Revision ID: 75ec8f84a2b1
Revises: a0a23a61e7cd
Create Date: 2025-10-10 11:56:15.871424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75ec8f84a2b1"
down_revision: Union[str, Sequence[str], None] = "a0a23a61e7cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "connector_access", "user", ["granted_by"], ["id"], use_alter=True
    )
    op.create_foreign_key(
        None, "connector_access", "user", ["user_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "connector_access", type_="foreignkey")
    op.drop_constraint(None, "connector_access", type_="foreignkey")
    # ### end Alembic commands ###
