"""add_expires_at_to_mcp_server_tokens

Revision ID: 910ded28396f
Revises: 1a19129680dc
Create Date: 2025-10-02 09:50:02.220168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "910ded28396f"
down_revision: Union[str, Sequence[str], None] = "1a19129680dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_server_tokens", sa.Column("expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_server_tokens", "expires_at")
    # ### end Alembic commands ###
