"""Fix mcp_server_tools schema with correct id type

Revision ID: 925f850e78fc
Revises: 756941f2c55a
Create Date: 2025-10-06 17:17:58.747880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "925f850e78fc"
down_revision: Union[str, Sequence[str], None] = "756941f2c55a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    tooltype_enum = sa.Enum("static", "dynamic", name="tooltype")
    tooltype_enum.create(op.get_bind())

    op.add_column(
        "mcp_server_tools",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "mcp_server_tools",
        sa.Column("tool", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "mcp_server_tools", sa.Column("tool_type", tooltype_enum, nullable=False)
    )
    op.add_column(
        "mcp_server_tools", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.drop_column("mcp_server_tools", "tools")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_server_tools",
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("mcp_server_tools", "is_active")
    op.drop_column("mcp_server_tools", "tool_type")
    op.drop_column("mcp_server_tools", "tool")
    op.drop_column("mcp_server_tools", "name")

    # Drop the enum type
    tooltype_enum = sa.Enum("static", "dynamic", name="tooltype")
    tooltype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
