"""Add user roles and connector access control

Revision ID: a0a23a61e7cd
Revises: d62570fd4964
Create Date: 2025-10-10 11:49:50.845873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0a23a61e7cd"
down_revision: Union[str, Sequence[str], None] = "d62570fd4964"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connector_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["mcp_connectors.id"],
        ),
        sa.ForeignKeyConstraint(["granted_by"], ["user.id"], use_alter=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("mcp_connectors", sa.Column("created_by", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("mcp_connectors_user_id_fkey"), "mcp_connectors", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "mcp_connectors", "user", ["created_by"], ["id"], use_alter=True
    )
    op.drop_column("mcp_connectors", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_connectors",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "mcp_connectors", type_="foreignkey")
    op.create_foreign_key(
        op.f("mcp_connectors_user_id_fkey"),
        "mcp_connectors",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_column("mcp_connectors", "created_by")
    op.drop_table("connector_access")
    # ### end Alembic commands ###
