"""Update models from models.py

Revision ID: ddbc6ca8bb99
Revises: 8dfd0a1243c3
Create Date: 2025-11-10 23:23:29.704018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = 'ddbc6ca8bb99'
down_revision: Union[str, Sequence[str], None] = '8dfd0a1243c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connector_access', 'connector_id',
               existing_type=sa.UUID(),
               nullable=True)
    # Add logo_name column if it doesn't exist
    try:
        op.add_column('mcp_connectors', sa.Column('logo_name', String(), nullable=False, server_default=''))
    except Exception:
        pass  # Column already exists
    
    # Drop index if it exists
    op.drop_index(op.f('uq_mcp_connectors_secret_md5'), table_name='mcp_connectors', postgresql_where='(secret IS NOT NULL)', if_exists=True)
    
    # Drop logo_url column if it exists
    try:
        op.drop_column('mcp_connectors', 'logo_url')
    except Exception:
        pass  # Column doesn't exist
    op.alter_column('mcp_servers', 'connector_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'connector_id',
               existing_type=sa.UUID(),
               nullable=False)
    
    # Add logo_url column if it doesn't exist
    try:
        op.add_column('mcp_connectors', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    except Exception:
        pass  # Column already exists
    
    # Create index if it doesn't exist
    try:
        op.create_index(op.f('uq_mcp_connectors_secret_md5'), 'mcp_connectors', [sa.literal_column('md5(secret::text)')], unique=True, postgresql_where='(secret IS NOT NULL)')
    except Exception:
        pass  # Index already exists
    
    # Drop logo_name column if it exists
    try:
        op.drop_column('mcp_connectors', 'logo_name')
    except Exception:
        pass  # Column doesn't exist
    
    op.alter_column('connector_access', 'connector_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
